<?php
$theme = $this->helper('mtdivas');
$equalHeight = $theme->getCfg('category_grid/equal_height');
$displayAddtocart = $theme->getCfg('category_grid/display_addtocart');
$displayAddtolink = $theme->getCfg('category_grid/display_addtolinks');
$compareHeader = $theme->getCfg('header/compare');
?>
<script type="text/javascript">
    <?php if ($equalHeight): ?>
    function setGridItemsEqualHeight($)
    {
        var winWidth = $(window).width();
        var SPACING = 20;
        if (winWidth >= 480)
        {
            $('.show-grid').removeClass("auto-height");
            var gridItemMaxHeight = 0;
            $('.show-grid > .item').each(function() {
                $(this).css("height", "auto");
                <?php if ($displayAddtocart == 2 || $displayAddtolink == 2): ?>
                var actionsHeight = $(this).find('.actions').height();
                $(this).css("padding-bottom", (actionsHeight + SPACING) + "px"); //Set new padding
                <?php endif; ?>
                gridItemMaxHeight = Math.max(gridItemMaxHeight, $(this).height());
            });
            $('.show-grid > .item').css("height", gridItemMaxHeight + "px");
        }
        else
        {
            $('.show-grid').addClass("auto-height");
            $('.show-grid > .item').css("height", "auto");
            $('.show-grid > .item').css("padding-bottom", "20px");
        }
    }
    <?php endif; ?>
    function setGridItem($){
        var winWidth = $(window).width();
        var col = <?php echo $theme->getCfg('category_grid/column_count');?>;
        if(winWidth > 768){
            newcol = col;
        }
        if(winWidth < 768 && winWidth >=640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_768');?>;
        }
        if(winWidth >=480 && winWidth <640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_640');?>;
        }
        if(winWidth < 480){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_480');?>;
        }
        $i = 0;
        $('.show-grid > .item').each(function() {
            $i++;
            $(this).removeClass('first');
            $(this).removeClass('last');
            if(($i-1)%newcol==0){
                $(this).addClass('first');
            }else if($i%newcol==0){
                $(this).addClass('last');
            }
        });
    }
    $mt(function($) {
        var winWidth = $(window).width();
        var winHeight = $(window).height();
        var windowResize_t;
        $(window).resize(function() {
            var winNewWidth = $(window).width();
            var winNewHeight = $(window).height();
            if (winWidth != winNewWidth || winHeight != winNewHeight)
            {
                clearTimeout(windowResize_t);
                windowResize_t = setTimeout(function() {
                    $(document).trigger("themeResize");
                    <?php if ($equalHeight): ?>
                    setGridItemsEqualHeight($);
                    <?php endif; ?>
                    setGridItem($);
                }, 200);
            }
            winWidth = winNewWidth;
            winHeight = winNewHeight;
        });
        <?php if($compareHeader):?>
        $('.mt-maincompare').hover(
            function () {
                $(this).addClass('compare-active').find('.mtajaxcompare').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('compare-active').find('.mtajaxcompare').stop().delay(200).slideUp();
            }
        );
        <?php endif; ?>
        $("#select-language").selectbox();
        $("#select-currency").selectbox();
        var text = $(".form-language a.sbSelector").text().toLowerCase();
        $(".form-language a.sbSelector").css({
            "background-image":"url('<?php echo Mage::getBaseUrl();?>media/wysiwyg/magenthemes/languages/"+text+".png')",
            "background-repeat":"no-repeat",
            "background-position":"left center"
        });

        //lazyLoad
        $("img.lazy").lazy({
            effect : "fadeIn",
            effectTime: 800,
            threshold: 50,
            afterLoad: function(element) {
                setGridItemsEqualHeight($);
            }
        });
        //Back to top
        $(window).scroll(function () {
            if ($(this).scrollTop() > 100) {
                $('#back-top').fadeIn();
            } else {
                $('#back-top').fadeOut();
            }
        });
        $('#back-top a').click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 800);
            return false;
        });
    });
    $mt(window).load(function(){
        <?php if ($equalHeight): ?>
        setGridItemsEqualHeight($mt);
        <?php endif; ?>
        setGridItem($mt);
    });
    // JavaScript Document
    $mt(document).ready(function(){
        $mt("[rel=tooltip]").tooltip();
        //add font icon awesome
        var selectToggle = '<i class="fa fa-angle-down"></i>',
            flextPrev = '<i class="fa fa-angle-left"></i>',
            revoNext = '<i class="fa fa-chevron-right"></i>',
            revoPrev = '<i class="fa fa-chevron-left"></i>',
            revoBullet = '<i class="fa fa-circle"></i>',
            flextNext = '<i class="fa fa-angle-right"></i>';

        $mt(".mt-social ul li .fa, .team-wap .social .fa, .flex-direction-nav a, .more-views .more-views-prev, .more-views .more-views-next").empty();
        $mt(".links li a").append("<i></i>");
        $mt(".links li.first i").addClass("fa fa-user");
        $mt(".links li a.top-link-wishlist i").addClass("fa fa-heart-o");
        $mt(".links li a.top-link-checkout i").addClass("fa fa-check");
        $mt(".links li.last i").addClass("fa fa-unlock-alt");
        $mt(".more-views").addClass("nav-wrapper-view");
        $mt(".sbToggle").append(selectToggle);
        $mt(".flex-direction-nav a.flex-prev, .more-views .more-views-prev").append(flextPrev);
        $mt(".flex-direction-nav a.flex-next, .more-views .more-views-next").append(flextNext);
        $mt(".level0.sub-wrapper, .level0 .sub-wrapper").prev('.level-top').append(selectToggle);
        $mt("#mtnav .sub-wrapper li.parent > a").append(flextNext);
        $mt(".tp-leftarrow.default").append(revoPrev);
        $mt(".tp-rightarrow.default").append(revoNext);
        $mt(".tp-bullets .bullet").append(revoBullet);

        var searchStyle2 = $mt('.header-layout2 .form-search');
        $mt('.search-style .fa-search').click(function(){
            if((searchStyle2).is(':visible')){
                $mt(searchStyle2).slideUp(400);
                $mt(this).removeClass('fa-arrows-alt').addClass('fa-search');
            }
            else{
                $mt(searchStyle2).slideDown(400);
                $mt(this).removeClass('fa-search').addClass('fa-arrows-alt');
            }

        });
    });

    $mt(".accordion-footer").addClass("accordion-show");
    $mt(".accordion-footer").click(function(){
        if($mt(this).parent().next().is(":visible")){
            $mt(this).addClass("accordion-show");
        }else{
            $mt(this).removeClass("accordion-show");
        }
        $mt(this).parent().next().toggle(400);
    });
</script>