<?php
/**
 * @category    MT
 * @package     MT_RevSlider
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<tr>
    <td colspan="2">
        <div class="">
            <div id="css_preview_wrapper" class="layer_animation_preview_wrapper css_preview_wrapper">
                <div id="css_preview">Text</div>
            </div>
        </div>
    </td>
</tr>
<style type="text/css">
    table.form-list{
        width: 100%;
    }
</style>