<?php
/**
 * @category    MT
 * @package     MT_Filter
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
    $bar = Mage::helper('mtfilter')->getConfig('mtfilter/general/bar');
    $barColor = '#'.Mage::helper('mtfilter')->getConfig('mtfilter/general/bar_color');
?>
<div id="<?php echo $this->getHash()?>" class="price-slider">
    <div id="<?php echo $this->getHash('-min')?>" class="price-slider-handle min"></div>
    <div id="<?php echo $this->getHash('-max')?>" class="price-slider-handle max"></div>
    <div id="<?php echo $this->getHash('-span')?>" class="price-slider-span"></div>
</div>
<div class="layer-price">
    <?php echo $this->getCurrencySymbol()?><span id="layer-price-min"></span>&nbsp;&nbsp;-&nbsp;&nbsp;<?php echo $this->getCurrencySymbol()?><span id="layer-price-max"></span>
</div>
<style type="text/css">
    .price-slider{
        height: 6px;
        width: 100%;
        background: #ececec;
        position: relative;
        margin: 10px 0;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    .price-slider .price-slider-handle{
        height: 20px;
        width: 20px;
        position: absolute;
        top: -7px;
    }
    .price-slider-handle.min{
        background: #3f3f3f;
    }
    .price-slider-handle.max{
        background: #3f3f3f;
    }
    .layer-price{
        text-align: center;
    }
</style>
<script type="text/javascript">
    window.mtFilter.initPriceFilter(<?php echo $this->getConfig()?>);
</script>