<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<tr>
    <td class="label">
        <label>
            <?php echo $this->getElement()->getLabel()?>
            <?php if ($this->getElement()->getRequired()):?><span class="required">*</span><?php endif ?>
        </label>
    </td>
    <td class="value">
        <input type="text" class="entities <?php if ($this->getElement()->getRequired()):?>required-entry<?php endif ?>" name="<?php echo $this->getElement()->getName()?>" readonly id="<?php echo $this->getElement()->getHtmlId()?>" value="<?php echo $this->getElement()->getValue() ?>">
        <a class="n-underline" href="javascript:void(0)" onclick="mtWidgetCategory.displayEntityChooser('<?php echo $this->getId() ?>')" title="<?php echo Mage::helper('mtwidget')->__('Open Chooser')?>">
            <img class="v-middle" src="<?php echo $this->getSkinUrl('images/rule_chooser_trigger.gif')?>"/>
        </a>
        <a class="n-underline" href="javascript:void(0)" onclick="mtWidgetCategory.hideEntityChooser('<?php echo $this->getId() ?>')" title="<?php echo Mage::helper('mtwidget')->__('Apply')?>">
            <img class="v-middle" src="<?php echo $this->getSkinUrl('images/rule_component_apply.gif')?>"/>
        </a>
        <a class="n-underline" href="javascript:void(0)" onclick="mtWidgetCategory.clearEntityValue('<?php echo $this->getId() ?>')" title="<?php echo Mage::helper('mtwidget')->__('Clear value')?>">
            <img class="v-middle" src="<?php echo $this->getSkinUrl('images/cancel_icon.gif')?>"/>
        </a>
        <p class="note">
            <span><?php echo $this->getElement()->getNote()?></span>
        </p>
        <div id="<?php echo $this->getId() ?>" class="tree"></div>
    </td>
</tr>
<style type="text/css">
    a.n-underline{text-decoration: none}
    #loading-mask{z-index: 2000}
</style>
<script type="text/javascript">
    window.mtWidgetCategory = new MTWidgetChooser('<?php echo $this->getCategoriesChooserUrl()?>');
    Ext.onReady(function(){
        Event.observe(document, 'categoryNode:changed', function(event){
            window. mtWidgetCategory.checkCategory(event);
        });
    });
</script>