<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<tr>
    <td class="label">
        <?php echo $this->getElement()->getLabel()?>
    </td>
    <td class="value">
        <input type="hidden" id="<?php echo $this->getElement()->getHtmlId()?>"/>
        <?php echo $this->getElement()->getData('after_element_html')?>
    </td>
</tr>
</script>