<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
$attributes = $this->getAttibuteOptions();
$id         = $this->getConfig('id');
$column     = $this->getConfig('column');
$scroll     = $this->getConfig('scroll');
$title      = $this->getConfig('widget_title');
?>
<?php if ($scroll == 1):?>
    <script type="text/javascript">
        $mt(document).ready(function(){
            var itemsCount = getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'column');
            $mt('#<?php echo $id?>').flexslider({
                direction: '<?php echo $this->getConfig('direction')?>',
                namespace: '<?php echo $this->getConfig('namespace')?>',
                slideshow: <?php echo $this->getConfig('autoplay')?>,
                controlsContainer: "#nav-wrapper-<?php echo $_id ?>",
                slideshowSpeed: <?php echo $this->getConfig('speed')?>,
                animationLoop: <?php echo $this->getConfig('loop')?>,
                controlNav: <?php echo $this->getConfig('paging')?>,
                animation: "slide",
                itemWidth: getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'width'),
                itemMargin: <?php echo $this->getConfig('margin')?>,
                minItems: itemsCount,
                maxItems: itemsCount,
                selector: ".slides > .slide",
                move: <?php echo $this->getConfig('move')?>,
                onResize: function(slider){
                    var itemsCount = getFlexSliderItemWidth('<?php echo $id?>', <?php echo $this->getConfig('responsive')?>, 'column');
                    slider.vars.minItems = itemsCount;
                    slider.vars.maxItems = itemsCount;
                }
            });
        });
    </script>
<?php endif ?>
<div class="slider-attribute-wrapper<?php echo $scroll==1 ? ' flexslider' : ''?>" id="<?php echo $id ?>">
    <div class="show-grid">
        <div class="main-heading">
            <div class="row">
                <div class="col-sm-10 col-md-10">
                    <?php if ($title):?>
                    <h3><?php echo $title?></h3>
                    <?php endif; ?>
                </div>
                <div class="col-sm-2 col-md-2">
                    <div id="nav-wrapper-<?php echo $_id ?>" class="nav-wrapper pull-right">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
    <ul class="slides">
        <?php foreach ($attributes as $attribute): ?>
            <li class="slide">
                <a href="<?php echo $attribute['link'] ?>" title="<?php echo Mage::helper('mtwidget')->__('%s', $attribute['label']) ?>">
                    <img class="img-responsive" src="<?php echo strpos($attribute['image'], 'http') === 0 ? $attribute['image'] : Mage::getBaseUrl('media') . $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <?php if ($this->getConfig('parallax')):?>
        <?php if ($this->getConfig('bg_type') == 'video'):?>
            <div id="<?php echo $id?>-video"></div>
            <script type="text/javascript">
                insertVideoBackground('<?php echo $id?>', <?php echo $this->getConfig('video')?>);
            </script>
            <style type="text/css">
                #<?php echo $id?>-video{position: absolute; z-index: -999; left: 0; top: 0;}
            </style>
            <div id="<?php echo $id?>-overlay" style="position: absolute;left: 0;top: 0;width: 100%;height: 100%;z-index: -999;" class="<?php echo $this->getConfig('bg_over')?>">
                <i class="fa fa-spinner fa-spin" style="font-size: 30px;color: #fff;"></i>
            </div>
        <?php else: ?>
            <script type="text/javascript" src="<?php echo Mage::getUrl('js')?>mt/extensions/$mt/plugins/$mt.parallax-1.1.3.js"></script>
            <script type="text/javascript">
                $mt(function(){
                    $mt('#<?php echo $id?>').parallax('50%', <?php echo $this->getConfig('bg_vel')?>);
                });
            </script>
        <?php endif ?>
        <style type="text/css">
            #<?php echo $id?>{
                    <?php if ($this->getConfig('bg_type') == 'image'):?>
                    background-image: url(<?php echo $this->getConfig('bg_url')?>);
                    background-size: <?php echo $this->getConfig('bg_size')?>;
                    background-position: <?php echo $this->getConfig('bg_position')?>;
                    background-repeat: <?php echo $this->getConfig('bg_repeat')?>;
                    background-attachment: fixed;
                    <?php endif ?>
                    position: relative;
                    z-index:0;
                    overflow: hidden;
                }
            <?php if ($this->getConfig('bg_over') != 'none'):?>
            .twoxtwo{
                background: url(<?php echo Mage::getUrl('js')?>mt/widget/images/gridtile.png) repeat;
            }
            .twoxtwowhite{
                background: url(<?php echo Mage::getUrl('js')?>mt/widget/images/gridtile_white.png) repeat;
            }
            .threexthree{
                background: url(<?php echo Mage::getUrl('js')?>mt/widget/images/gridtile_3x3.png) repeat;
            }
            .threexthreewhite{
                background: url(<?php echo Mage::getUrl('js')?>mt/widget/images/gridtile_3x3_white.png) repeat;
            }
            <?php endif ?>
        </style>
    <?php endif ?>
</div>
<style>
    .attribute-slider-wrapper .slide {text-align: center}
    .attribute-slider-wrapper .slide a {margin: 2px; display: inline-block}
</style>