<?php
/**
 * @category    MT
 * @package     MT_RevSlider
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<tr>
    <td class="label"></td>
    <td class="value" style="">
        <?php echo $this->getChildHtml('edit')?>
        <?php echo $this->getChildHtml('new')?>
    </td>
</tr>