<?php
/**
 * @category    MT
 * @package     MT_RevSlider
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<span>
    <div id="timeline">
        <div class="handle start" title="<?php echo $this->__('Drag to change Start Time')?>"></div>
        <div class="handle end" title="<?php echo $this->__('Drag to change End Time')?>"></div>
        <span class="min">ms</span>
        <span class="max">ms</span>
        <span class="span"></span>
    </div>
</span>
<div id="listLayers"></div>