<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<!-- navigation BOF -->
<div class="block block-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Categories'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="categories_nav" class="nav-accordion nav-categories">
            <?php echo $this->renderCategoriesMenuHtml(TRUE, TRUE, 0, 'level-top'); ?>
        </ul>
        <script type="text/javascript">
            $mt(document).ready(function() {
                $mt("#categories_nav").mtAccordionMenu({
                    accordion:true,
                    speed: 400,
                    closedSign: 'collapse',
                    openedSign: 'expand',
                    mouseType: 0,
                    easing: 'easeInOutQuad'
                });
            });
        </script>
    </div>
</div>
<!-- navigation EOF -->