<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     MT
 * @package      MT_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       MagentoThemes.net
 * @email        support@magentothemes.net
 * ------------------------------------------------------------------------------
 *
 */
?>
<?php
$config = Mage::getStoreConfig('ajaxcart/ajaxcart_config');
?>
<?php
    $_item = $this->getItem();
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
    $canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
?>
<li class="item">
    <?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(100, 100)->setWatermarkSize('30x10'); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(100, 100)->setWatermarkSize('30x10'); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></span>
    <?php endif; ?>
    <div class="product-details row-fluid show-grid">
        <p class="product-name clearfix"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->htmlEscape($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
		<?php /* <strong><?php echo $this->getQty() ?></strong> x */ ?>
        <div class="items clearfix">
        <?php if ($canApplyMsrp): ?>
            <span class="map-cart-sidebar-item"><?php echo $this->__('See price before order confirmation.'); ?></span>
        <?php else: ?>
        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <?php echo $this->__('Excl. Tax'); ?>:
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <br /><?php echo $this->__('Incl. Tax'); ?>:
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
            <?php else: ?>
                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
        </div>
		<div class="access clearfix">
			<?php if($config['enable_ajaxcart']){?>
				<a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit') ?>" class="btn-edit">
					<span class="icon"></span>
					<?php echo $this->__('Edit')?>
				</a>
				<a  href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove') ?>" class="btn-remove deletecart">
					<span class="icon"></span>
					<?php echo $this->__('Remove') ?>
				</a>
				<?php }else{?>
				<a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');" class="btn-remove">
					<span class="icon"></span>
					<?php echo $this->__('Remove') ?>
				</a>
			<?php }?>
			<?php if ($isVisibleProduct): ?>
			<?php endif ?>
		<?php endif; //Can apply MSRP ?>
		</div>


        <?php if ($_options = $this->getOptionList()):?>
        <div class="truncated">
            <div class="truncated_full_value">
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                    <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                    <dd>
                        <?php if (is_array($_option['value'])): ?>
                        <?php echo nl2br(implode("\n", $_option['value'])) ?>
                        <?php else: ?>
                        <?php echo $_option['value'] ?>
                        <?php endif; ?>
                    </dd>
                    <?php endforeach; ?>
                </dl>
            </div>
		  <?php /* <a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a> */ ?>
        </div>
        <?php endif; ?>
    </div>
</li>
